site_name: !!python/object/apply:os.getenv ["CI_PROJECT_TITLE"]
site_url: !!python/object/apply:os.getenv ["CI_PAGES_URL"]
site_description: Functional Docker Images
repo_url: !!python/object/apply:os.getenv ["CI_PROJECT_URL"]
repo_name: !!python/object/apply:os.getenv ["CI_PROJECT_PATH"]
repo_name: GitLab
edit_uri: tree/master

extra_css:
  - assets/stylesheets/custom.css
  - assets/stylesheets/color.css

docs_dir: docs
theme:
  favicon: .meta/theme/assets/images/favicon.png
  name: material
  custom_dir: .meta/theme
  font:
    text: Ubuntu
    code: Ubuntu Mono
  # features:
  #   - tabs
  icon:
    repo: fontawesome/brands/git-alt
    logo: fontawesome/solid/atom

plugins:
  - search:
  # - macros:
  - minify:
      minify_html: true
  - awesome-pages:
      filename: .pages
      collapse_single_pages: true
  - markdownextradata: {}

extra:
  external_links:
    functions: !!python/object/apply:os.getenv ["CI_PROJECT_URL"]
    web: !!python/object/apply:os.getenv ["CI_PROJECT_PATH"]
    pages: !!python/object/apply:os.getenv ["CI_PAGES_DOMAIN"]
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/donaldrich/
    - icon: fontawesome/brands/github
      link: https://github.com/donaldrich80/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/donaldrich/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/don-aldrich-48a51815/

markdown_extensions:
  - admonition:
  - codehilite:
  - footnotes:
#   - markdown.extensions.toc:
#       slugify: !!python/name:pymdownx.slugs.uslugify
  - markdown.extensions.smarty:
      smart_quotes: false
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.md_in_html:
  - meta:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite:
  - pymdownx.magiclink:
      # repo_url_shortener: true
      # repo_url_shorthand: true
      # social_url_shorthand: true
      # social_url_shortener: true
      # provider: 'gitlab'
      # user: 'donaldrich'
      # repo: 'modular-gitlab-ci'
  - pymdownx.mark:
  - pymdownx.progressbar:
  - pymdownx.smartsymbols:
  - pymdownx.snippets:
      base_path: meta/.snippets
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
#       permalink: ""
#         - name: math
#           class: arithmatex
#           format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
  - pymdownx.tilde:
#   - pymdownx.highlight:
#       extend_pygments_lang:
#         - name: php-inline
#           lang: php
#           options:
#             startinline: true
#         - name: pycon3
#           lang: pycon
#           options:
#             python3: true
#       linenums_style: pymdownx-inline
#   - pymdownx.inlinehilite:
#       custom_inline:
#         - name: math
#           class: arithmatex
#           format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
#   - pymdownx.escapeall:
#       hardbreak: True
#       nbsp: True
#   - pymdownx.striphtml:
#   - pymdownx.keys:
#       separator: "\uff0b"
